In [ ]:
pip install transformers

In [ ]:
import numpy as np
import random
import tensorflow as tf
from transformers import AutoTokenizer
from transformers import TFGPT2LMHeadModel
#gpt2 -> finetuning -> 한국어 gpt2모델

In [ ]:
model=TFGPT2LMHeadModel.from_pretrained("skt/kogpt2-base-v2",from_pt=True)

pytorch_model.bin:   0%|          | 0.00/513M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['lm_head.weight', 'transformer.h.9.attn.masked_bias', 'transformer.h.6.attn.masked_bias', 'transformer.h.4.attn.masked_bias', 'transformer.h.11.attn.masked_bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.7.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.5.attn.masked_bias', 'transformer.h.2.attn.masked_bias', 'transformer.h.10.attn.masked_bias', 'transformer.h.8.attn.masked_bias', 'transformer.h.3.attn.masked_bias']
- This IS expected if you are initializing TFGPT2LMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFGPT2LMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassifica

In [ ]:
tokenizer=AutoTokenizer.from_pretrained("skt/kogpt2-base-v2")

tokenizer.json:   0%|          | 0.00/2.83M [00:00<?, ?B/s]

In [ ]:
sent="프로젝트를 성공하려면 팀원들은 "

In [ ]:
input_ids=tokenizer.encode(sent)

In [ ]:
input_ids=tf.convert_to_tensor([input_ids])         #리스트 구조를 텐서로 변환, 2차원 구조로 출력 해줘야함

In [ ]:
input_ids

<tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[21835, 12498, 10363, 19352, 13717, 34686,   739]], dtype=int32)>

In [ ]:
output=model.generate(input_ids,
               max_length=158,
               repetition_penalty=2.0,     #반복과 관련된 penalty -> 문장 생성할때 앞에서 이미 등장한 단어가 또 나오는거에 대해 penalty를 어떻게 줄것인가,
                                           #갚을 크게 주면 앞에서 등장한 단어 또 안나옴, 작게 주면 또 나올수 있음
               use_cache=True)

In [ ]:
output

<tf.Tensor: shape=(1, 158), dtype=int32, numpy=
array([[21835, 12498, 10363, 19352, 13717, 34686,   739,  7569,  6824,
         9689,  9290,  9659,  7991,  9178,  8612, 25323, 24804, 20580,
         9022, 19118, 11280, 18314, 14319,  9021,  9604, 12748, 10206,
         8146,  7399, 10943, 22301, 37921,  9194, 16941, 14921,  9109,
         8461, 16944,  7877, 12123,  9199,  9029,  6947, 11097, 10607,
         8552,  8137, 11348,  9038,  9925, 15154,  9280, 17451, 11448,
        12016, 18427,  9136,  9018, 23191,  9430, 49429, 15997, 20659,
         8149,  9025,  9080, 10586, 25012, 10341,  9243, 45487,  8243,
         7824, 11183, 11380,  8765,  9804,  9599, 10063,  8056,  8711,
         9609, 19864, 11570,  8148, 11841,  9366, 45272, 30748,  9031,
          377,  9131,  7530, 29843,  7623, 27087, 15954,  7633,  8359,
        27837,  9453,  7426, 14354,  8022, 13229,  9069,  6962, 47002,
        19303,  9135, 13872,     8,  9426, 22771, 16322, 35576,   418,
          414,  9667, 12199, 

In [ ]:
output_ids=output.numpy().tolist()[0]   #단일구조 리스트로 만듬 -> 토크나이저의 decode함수로 전달하기 위해 단일 리스트 구조로 변경함
output_ids

[21835,
 12498,
 10363,
 19352,
 13717,
 34686,
 739,
 7569,
 6824,
 9689,
 9290,
 9659,
 7991,
 9178,
 8612,
 25323,
 24804,
 20580,
 9022,
 19118,
 11280,
 18314,
 14319,
 9021,
 9604,
 12748,
 10206,
 8146,
 7399,
 10943,
 22301,
 37921,
 9194,
 16941,
 14921,
 9109,
 8461,
 16944,
 7877,
 12123,
 9199,
 9029,
 6947,
 11097,
 10607,
 8552,
 8137,
 11348,
 9038,
 9925,
 15154,
 9280,
 17451,
 11448,
 12016,
 18427,
 9136,
 9018,
 23191,
 9430,
 49429,
 15997,
 20659,
 8149,
 9025,
 9080,
 10586,
 25012,
 10341,
 9243,
 45487,
 8243,
 7824,
 11183,
 11380,
 8765,
 9804,
 9599,
 10063,
 8056,
 8711,
 9609,
 19864,
 11570,
 8148,
 11841,
 9366,
 45272,
 30748,
 9031,
 377,
 9131,
 7530,
 29843,
 7623,
 27087,
 15954,
 7633,
 8359,
 27837,
 9453,
 7426,
 14354,
 8022,
 13229,
 9069,
 6962,
 47002,
 19303,
 9135,
 13872,
 8,
 9426,
 22771,
 16322,
 35576,
 418,
 414,
 9667,
 12199,
 7187,
 15179,
 9148,
 14472,
 13834,
 9168,
 9563,
 37043,
 16858,
 7244,
 9741,
 8023,
 17698,
 13363,
 91

In [ ]:
tokenizer.decode(output_ids)

'프로젝트를 성공하려면 팀원들은 뭔가 새로운 것을 만들어야 한다.\n팀원들이 아이디어를 내면 그 아이디어는 곧바로 실행으로 이어지기 때문이다.\n이런 점에서 이번 행사는 \'아이디어 마켓플레이스\'라는 것이 있다.\n그동안 아이템을 발굴하고 사업화하는 데 어려움을 겪었던 중소기업들이 이 행사를 통해 참신한 제품을 선보일 수 있는 좋은 기회가 될 것으로 기대된다.\n중소기업중앙회 관계자는 "올해 처음 열리는 행사인 만큼 많은 기업들이 참여할 것"이라며 "이번 행사가 중소벤처기업의 판로 개척에 도움이 되길 바란다"고 말했다.</d> 한국토지주택공사(LH)는 지난달 30일부터 오는 10일까지 서울 강남구 삼성동 코엑스에서 열린 ‘2018 대한민국 부동산 엑스포’에 참가했다고 1일 밝혔다.\n지난해에 비해 관람객 수는 약 30% 늘었다.\n특히'

In [ ]:
output=model(input_ids)

In [ ]:
output.logits

<tf.Tensor: shape=(1, 7, 51200), dtype=float32, numpy=
array([[[-6.140402  , -5.859082  , -5.178856  , ..., -3.4393203 ,
         -2.6944485 , -3.563459  ],
        [-4.420429  , -3.9891706 , -4.9624968 , ..., -2.7080774 ,
         -2.3276203 ,  2.5232625 ],
        [-4.832242  , -4.7837524 , -5.5392814 , ..., -6.709307  ,
         -2.8316736 , -0.70310223],
        ...,
        [-6.8753753 , -6.2472878 , -7.268092  , ..., -6.7852583 ,
         -5.301508  , -4.266958  ],
        [-5.551777  , -4.89018   , -6.23775   , ..., -0.67808044,
         -4.399397  , -1.0230882 ],
        [-1.3097541 , -1.5740259 , -2.4513245 , ..., -3.177927  ,
         -2.6688612 , -0.8659774 ]]], dtype=float32)>

In [ ]:
output.logits[0,-1]

<tf.Tensor: shape=(51200,), dtype=float32, numpy=
array([-1.3097541, -1.5740259, -2.4513245, ..., -3.177927 , -2.6688612,
       -0.8659774], dtype=float32)>

In [ ]:
top10=tf.math.top_k(output.logits[0,-1],k=10)

In [ ]:
top10.indices.numpy()  #어레이 형태로 바꿈

array([ 7569,  7570,  7337,     5,  7099,  7802,  8541,  6910,  7868,
       11578], dtype=int32)

In [ ]:
tokenizer.convert_ids_to_tokens(top10.indices.numpy())

['뭔', '뭘', '똘', '<unk>', '넥', '섹', '턴', '괜', '쉼', '컴퓨']

In [ ]:
sent="인공지능 전문가가 되기 위해서"

In [ ]:
input_ids=tokenizer.encode(sent)

In [ ]:
input_ids

while(len(input_ids)<50):
    output = model(np.array([input_ids]))
    top5 = tf.math.top_k(output.logits[0, -1], k=5)  # 예상되는 상위 5개 단어 가져옴
    token_id = random.choice(top5.indices.numpy())   #5개 단어중 하나를 뽑아 input_ids에 넣음
    input_ids.append(token_id)
tokenizer.decode(input_ids)

'인공지능 전문가가 되기 위해서 필요한 교육 과정”이라면서 “앞서 교육과학기술부 대학구조조정이 마무리돼 대학들이 속속 졸업을 앞두고 있지만 취업 준비생은 많지 않은 만큼 이번에 취업준비생과 대학생의 눈높이에서 차별화되고'