In [ ]:
"""
파이토치
- n차원 텐서
- 신경망 구성하고 학습하는 과정에서의 자동 미분
비전분야(이미지, 영상) -> 3차원 텐서 (batch size, width, height)
자연어 처리 분야 -> 3차원 텐서 (batch size, length, dimension)   =>분야에 따라 표현 방법이 다름

"""

In [1]:
import numpy as np

In [ ]:
#넘파이로 텐서를 만드는 방법 
#1차원 텐서

In [9]:
t=np.array([1,2,3,4])
t
t.ndim #몇차원 텐서
t.shape #텐서의 크기, (4,)는 (1,4)를 의미함 

(4,)

In [10]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [14]:
t
t.ndim #몇 차원 텐서
t.shape #텐서의 크기 (4,3)

(4, 3)

In [15]:
#파이토치로 텐서 만드는 방법

In [ ]:
#클래스 : 설계도면, 붕어빵기계, 벽돌공장
#객체: 클래스로부터 생성되는 실체
# 설계도면 -> 실제건물
# 붕어빵기계 -> 붕어빵
# 벽돌공장 -> 벽돌
# 메서드 : 객체가 수행하는 동작(기능)
# 속성(어트리뷰트) :객체의 특성 
# 객체지향(적) 프로그래밍
# ex) 절차지향적 사례
# -붕어빵 기계로 붕업빵을 판매하던 시대가 지나가고 잉어빵 시대가 도래, 붕어빵 기계는 못쓰게 됨 
# ->잉어빵 기계 새롭게 제작
# ex)객체지향적 사례
# 붕어빵 기계로 붕어빵을 판매하던 시대가 지나가고
# 잉어빵 시대가 도래, 붕어빵 기계를 재사용(붕어빵 기계의 메서드, 속성 중에서 그대로 사용할 것은 사용하고,
#                        변경할것은 변경, 버릴것은 버리고)

In [17]:
pip install torch

   ---------------------------------------- 0.0/192.3 MB ? eta -:--:--
   ---------------------------------------- 0.4/192.3 MB 11.6 MB/s eta 0:00:17
   ---------------------------------------- 1.0/192.3 MB 15.1 MB/s eta 0:00:13
   ---------------------------------------- 1.7/192.3 MB 18.1 MB/s eta 0:00:11
    --------------------------------------- 2.6/192.3 MB 18.2 MB/s eta 0:00:11
    --------------------------------------- 3.6/192.3 MB 20.8 MB/s eta 0:00:10
    --------------------------------------- 4.7/192.3 MB 23.3 MB/s eta 0:00:09
   - -------------------------------------- 5.9/192.3 MB 25.2 MB/s eta 0:00:08
   - -------------------------------------- 7.4/192.3 MB 26.2 MB/s eta 0:00:08
   - -------------------------------------- 8.7/192.3 MB 27.8 MB/s eta 0:00:07
   -- ------------------------------------- 9.7/192.3 MB 28.2 MB/s eta 0:00:07
   -- ------------------------------------- 10.7/192.3 MB 28.4 MB/s eta 0:00:07
   -- ------------------------------------- 11.8/192.3 MB 3

In [18]:
import torch

In [19]:
t=torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t
#클래스(FloatTensor) : 대문자로 시작 

tensor([0., 1., 2., 3., 4., 5., 6.])

In [27]:
t.dim()
t.shape  #속성
t.size() #함수(메서드), 내차.달린다()  자동차(클래스)
# '자동차'클래스로부터 파생된 실체(객체)가 '내차'

torch.Size([7])

In [29]:
"""
class FloatTensor:
    속성 (특성)
    함수 (동작)
"""

'\nclass FloatTensor:\n    속성 (특성)\n    함수 (동작)\n'

In [31]:
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [33]:
t[3]

tensor(3.)

In [34]:
t[2:5]

tensor([2., 3., 4.])

In [35]:
t[:3]

tensor([0., 1., 2.])

In [36]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

In [37]:
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [38]:
t.dim()

2

In [39]:
t.size()

torch.Size([4, 3])

In [40]:
t[:,1] #2번째 차원의 첫번째만 가지고 온다

tensor([ 2.,  5.,  8., 11.])

In [41]:
t[:,1].size()

torch.Size([4])

In [ ]:
# 행렬 연산(덧셈,뺄셈) : 두 행렬의 크기가 같아야 함
# 행렬 연산(곱셈)   : 두행렬의 마지막 차원과 첫번째 차원이 일치
# 브로드 캐스팅 : 두 행렬 크기를 맞춰서 연산 가능토록 함

In [42]:
t1=torch.FloatTensor([[1,1]])
t2=torch.FloatTensor([[2,2]])

In [47]:
t1.shape
t1+t2

tensor([[3., 3.]])

In [48]:
t3=torch.FloatTensor([[1,1]])  #(1,2)
t4=torch.FloatTensor([[3]])  #(1,) -> (1,2) =>브로드캐스팅됨(자동 변경)

In [49]:
t3+t4

tensor([[4., 4.]])

In [56]:
#2*1 + 1*2
t5=torch.FloatTensor([[1,3]])  #[[1,3],
                               #[1,3]] 으로 브로드 캐스팅 됨
t6=torch.FloatTensor([[1],[3]])  #[[1],     [[1],[1],
                                 #[3]]      [3],[3]]     으로 브로드 캐스팅 됨

In [57]:
t5.shape

torch.Size([1, 2])

In [58]:
t6.shape

torch.Size([2, 1])

In [59]:
t5+t6  #(2,2)

tensor([[2., 4.],
        [4., 6.]])

In [60]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [61]:
m1.shape

torch.Size([2, 2])

In [62]:
m2.shape

torch.Size([2, 1])

In [63]:
m1.matmul(m2) #matmul= 행렬 곱셈

tensor([[ 5.],
        [11.]])

In [64]:
m1*m2       #m2에서 브로드캐스팅이 발생해 2*2로 변환되어 요소간 곱셈 발생

tensor([[1., 2.],
        [6., 8.]])

In [65]:
t=torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [66]:
t.mean()

tensor(2.5000)

In [67]:
t.mean(dim=0)  # 차원을 줘서 평균을 구할수 있음 -> dim=0은 첫번째 차원, 행렬에서는 행단위로 평균 구해짐 
# -> 행에 해당하는 차원을 제거 한다(열만 남긴다) = 2차원 구조 행렬 -> 1차원 벡터로 바뀜 

tensor([2., 3.])

In [71]:
t.mean(dim=1) #dim=1은 두번째 차원, 행렬에서는 열, 열을 제거 -> 행만 남음 

tensor([1.5000, 3.5000])

In [345]:
t=torch.FloatTensor([[1,2],[3,4]])

In [346]:
t

tensor([[1., 2.],
        [3., 4.]])

In [347]:
t.sum()

tensor(10.)

In [349]:
t.sum(dim=0)

tensor([4., 6.])

In [350]:
t.sum(dim=1)

tensor([3., 7.])

In [351]:
t.sum(dim=-1)  #마지막 차원 제거함 = 열 제거

tensor([3., 7.])

In [352]:
t.max()

tensor(4.)

In [82]:
t.max(dim=0)  #행 제거  , indeices=argmax : 최대값의 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [83]:
import numpy as np

In [84]:
import torch

In [353]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [354]:
ft

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [355]:
ft.shape

torch.Size([2, 2, 3])

In [356]:
#view : 텐서 크기 변경 함수, (-1,3)은 (?,3)으로 표기하기도 함 
#[2,2,3] 3차원 텐서를 2차원 텐서로 변경 (-1,3) -> 열은 정해져 있고 행의 갯수를 알아서 지정해줌
#12개 요소 구성된 3차원 텐서 -> (행:?, 열:3) => 행:4 =>(4,3)
ft.view([-1,3]) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [ ]:
ft.view([-1,5]) 
#고정하고자 하는 열이 전체에서 나눠 떨어 져야함으로 에러발생

In [90]:
ft.view([4,-1]) #행은 4개로 고정, 열은 알아서 계산해라

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [91]:
ft  #(2,2,3) -> (?,1,3)
ft.view([-1,1,3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [93]:
ft=torch.FloatTensor([[0],[1],[2]])
ft  # 3*1 행렬

tensor([[0.],
        [1.],
        [2.]])

In [94]:
ft.squeeze()  #크키가 1인 차원을 제거 

tensor([0., 1., 2.])

In [95]:
ft2=torch.FloatTensor([[0,1],[1,2],[2,3]])
ft2

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [96]:
ft2.squeeze()  #행 크기 :3, 열 크기 :2 -> 크기가 1인 차원이 없으므로 제거 작업 수행하지 않음 

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [97]:
#unsqueeze : 크기가 1인 차원을 특정 위치에 추가

In [99]:
ft = torch.Tensor([0, 1, 2])
ft

tensor([0., 1., 2.])

In [100]:
ft.unsqueeze(0)  #크기가 1인 차원이 첫번째 축에 추가 (1차원 ->2차원) -> (1,3) 

tensor([[0., 1., 2.]])

In [101]:
ft.unsqueeze(1)  #크기가 1인 차원이 두번째 축에 추가 (1차원 ->2차원) ->(3,1)

tensor([[0.],
        [1.],
        [2.]])

In [102]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [103]:
lt.float() #일괄적으로 float형태로

tensor([1., 2., 3., 4.])

In [104]:
bt = torch.ByteTensor([True,False,True,False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [106]:
bt = torch.ByteTensor([123456789876541,False,True,False])
print(bt)

RuntimeError: value cannot be converted to type uint8 without overflow

In [107]:
bt = torch.FloatTensor([1231242443567564354,False,True,False])
print(bt)
#Byte 텐서보다 플롯 텐서가 출력 가능 값이 더 커서 출력됨

tensor([1.2312e+18, 0.0000e+00, 1.0000e+00, 0.0000e+00])


In [105]:
bt.long()

tensor([1, 0, 1, 0])

In [108]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [109]:
x

tensor([[1., 2.],
        [3., 4.]])

In [110]:
y

tensor([[5., 6.],
        [7., 8.]])

In [112]:
torch.cat([x,y])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [113]:
torch.cat([x,y], dim=0)  #dim=0을 줌으로 첫번째 차원을 기준으로 연결됨

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [114]:
torch.cat([x,y], dim=1)  #두번째 차원을 기준으로 연결됨

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [115]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [116]:
z

tensor([3., 6.])

In [117]:
torch.stack([x,z,y]) #기입한 순서대로 합쳐짐

tensor([[1., 4.],
        [3., 6.],
        [2., 5.]])

In [118]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [119]:
#텐서의 크기는 그대로 두되, 새롭게 0 또는 1로 값을 채우는것 
torch.ones_like(x)  # ->shape은 그대로, 값은 모두 1로 채워짐
torch.zeros_like(x)  #

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [120]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [121]:
x

tensor([[1., 2.],
        [3., 4.]])

In [122]:
x*2

tensor([[2., 4.],
        [6., 8.]])

In [123]:
x.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [125]:
x.mul_(2) #_를 써주면 inplace함수 처럼 기존 데이터 바꿔줌

tensor([[2., 4.],
        [6., 8.]])

In [127]:
x

tensor([[2., 4.],
        [6., 8.]])

In [128]:
result = 0  #전역 변수

In [134]:
# 지역변수 :변수명은 같지만 두개의 변수는 다른 변수다 , 함수 내부에 생성된 변수는 함수 블럭 안에서만 사용되어지는 변수로 지역변수라 함
def add(num):
    global result   #global을 사용하면 함수 안에 없어도 변수 사용가능 
    #result=1
    result +=num
    return result

In [135]:
add(3)

3

In [136]:
print(result)

3


In [150]:
result1 = 0
result2 = 0

In [ ]:
def add1(num):
    global result1
    result1 += num
    return result1
    

In [142]:
def add2(num):
    global result2
    result2 += num
    return result2

In [152]:
print(add1(3))
print(add1(4))

3
7


In [153]:
print(add2(2))
print(add2(6))

2
8


In [141]:
print(result1)

3


In [159]:
class Calculator:
    def __init__(self):  #클래스 -> 객체 생성될때 자동 호출(생성자 함수)
        self.result = 0
        print("생성자 호출됨")
    
    def add(self, num): 
        self.result += num
        print("add함수 호출됨")
        return self.result

In [160]:
cal1=Calculator()  #클래스 ->객체 생성
cal2=Calculator()

생성자 호출됨
생성자 호출됨


In [161]:
cal1.add(3)

add함수 호출됨


3

In [162]:
cal1.add(4)

add함수 호출됨


7

In [163]:
cal2.add(2)

add함수 호출됨


2

In [164]:
cal2.add(6)

add함수 호출됨


8

In [165]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [245]:
torch.manual_seed(1)

In [246]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [247]:
x_train.shape

torch.Size([3, 1])

In [248]:
W=torch.zeros(1,requires_grad=True)  #requires_grad=True는 W는 변수

In [249]:
b=torch.zeros(1,requires_grad=True) #requires_grad=True는 b는 변수

In [250]:
#초기 모델 가설 함수 : y = 0*x + 0
hx=W * x_train + b  #예측값

In [251]:
hx

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [252]:
 # cost
    
cost=torch.mean((hx - y_train) ** 2)
cost

tensor(18.6667, grad_fn=<MeanBackward0>)

In [253]:
optimizer=optim.SGD([W,b],lr=0.01) 

In [254]:
optimizer.zero_grad()  #미분을 해서 구한 기울기를 0으로 초기화 해줌
cost.backward()  #W, b에 대한 기울기가 계산
optimizer.step() #W,b에 대한 업데이트

In [255]:
optimizer=optim.SGD([W,b],lr=0.01) 
for epoch in range(2000):
    hx=W * x_train + b
    cost=torch.mean((hx - y_train) ** 2)
    optimizer.zero_grad()  #미분을 해서 구한 기울기를 0으로 초기화 해줌, 안하면 이전에 구한 기울기 계속 더해짐
    cost.backward()  #W, b에 대한 기울기가 계산
    optimizer.step() #W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, W.item(), b.item(), cost.item())

0 0.35271114110946655 0.15093332529067993 14.770962715148926
100 1.746303915977478 0.5766831636428833 0.04793928191065788
200 1.8005797863006592 0.45332908630371094 0.02962353825569153
300 1.8432375192642212 0.3563580811023712 0.018305568024516106
400 1.876770257949829 0.28012996912002563 0.011311731301248074
500 1.9031305313110352 0.22020739316940308 0.00698992470279336
600 1.923851728439331 0.17310291528701782 0.004319347441196442
700 1.940140724182129 0.13607460260391235 0.0026691032107919455
800 1.9529448747634888 0.10696704685688019 0.001649328856728971
900 1.9630104303359985 0.08408597856760025 0.0010191872715950012
1000 1.970922827720642 0.06609929352998734 0.0006298050284385681
1100 1.9771424531936646 0.05196019262075424 0.0003891797096002847
1200 1.9820321798324585 0.04084517061710358 0.0002404868573648855
1300 1.9858757257461548 0.03210793808102608 0.00014860653027426451
1400 1.9888969659805298 0.025239810347557068 9.182951907860115e-05
1500 1.99127197265625 0.019840871915221

In [256]:
W   #W:2

tensor([1.9974], requires_grad=True)

In [257]:
b    #b:0

tensor([0.0060], requires_grad=True)

In [258]:
W.item() #W가 가지고 있는 값 출력

1.9973737001419067

In [259]:
W.item()*5 + b.item()   #예측값 구함

9.992838663514704

In [260]:
w = torch.tensor(2.0, requires_grad=True)


In [261]:
y=w**2

In [262]:
y

tensor(4., grad_fn=<PowBackward0>)

In [263]:
z=2*y+5

In [264]:
z

tensor(13., grad_fn=<AddBackward0>)

In [265]:
z.backward()

In [267]:
w.grad  #z수식을 w로 미분한 값

tensor(8.)

In [306]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [307]:
x1_train.shape

torch.Size([5, 1])

In [308]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [310]:
optimizer=optim.SGD([w1,w2,w3,b],lr=1e-5) #0.01 <= lr <= 0.001
#1* 10의 -5 승 = 1* 0.00001 = 1e-5

for epoch in range(2000):
    hx=w1 * x1_train + w2 * x2_train+ w3 * x3_train + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%10 ==0:
        
        print(epoch, w1.item(), w2.item(), w3.item(), b.item(), cost.item())

0 0.7570484280586243 0.5713934898376465 0.6820759177207947 0.01059654913842678 0.7543893456459045
10 0.7573939561843872 0.5710384249687195 0.682084858417511 0.010609765537083149 0.751927375793457
20 0.7577386498451233 0.5706843137741089 0.6820935606956482 0.010622975416481495 0.7494856119155884
30 0.7580825686454773 0.5703312754631042 0.6821020841598511 0.010636175982654095 0.7470517754554749
40 0.7584256529808044 0.5699792504310608 0.6821103692054749 0.010649370029568672 0.7446351051330566
50 0.7587679028511047 0.5696282982826233 0.6821185350418091 0.010662556625902653 0.7422196269035339
60 0.7591094374656677 0.5692782998085022 0.6821264624595642 0.010675736702978611 0.7398267984390259
70 0.7594501376152039 0.5689293146133423 0.682134211063385 0.010688906535506248 0.7374515533447266
80 0.7597898840904236 0.5685813426971436 0.6821417808532715 0.010702070780098438 0.7350757718086243
90 0.7601290345191956 0.5682343244552612 0.6821490526199341 0.010715227574110031 0.7327166199684143
100 0

1070 0.7897573113441467 0.5386559963226318 0.682056188583374 0.011969216167926788 0.5526240468025208
1080 0.7900260090827942 0.538395345211029 0.6820477843284607 0.01198167447000742 0.5512160062789917
1090 0.7902941107749939 0.5381355285644531 0.6820391416549683 0.011994126252830029 0.549821138381958
1100 0.7905616164207458 0.5378764867782593 0.682030439376831 0.01200657244771719 0.5484288930892944
1110 0.79082852602005 0.5376182198524475 0.6820214986801147 0.012019013054668903 0.5470463037490845
1120 0.7910947799682617 0.5373606085777283 0.6820125579833984 0.01203144621104002 0.5456733107566833
1130 0.7913604974746704 0.5371037721633911 0.6820034384727478 0.012043870985507965 0.5442969799041748
1140 0.7916256189346313 0.536847710609436 0.6819939613342285 0.012056292966008186 0.5429391860961914
1150 0.7918899655342102 0.536592423915863 0.681984543800354 0.012068708427250385 0.5415868163108826
1160 0.7921538352966309 0.5363379120826721 0.6819750070571899 0.012081117369234562 0.540235936

In [311]:
 w1.item()*90+ w2.item()*90+ w3.item()*90+ b.item()
#예상 수능 점수 : 180.95...

180.95364973694086

In [313]:
#                               x1   x2   x3
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [314]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [317]:
#w1 = torch.zeros(1, requires_grad=True)
#w2 = torch.zeros(1, requires_grad=True)
#w3 = torch.zeros(1, requires_grad=True)


W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad=True)

In [319]:
optimizer=optim.SGD([W,b],lr=1e-5)

In [322]:
for epoch in range(2000):
    hx=x_train.matmul(W) + b
    cost=torch.mean((hx - y_train) ** 2)
    optimizer.zero_grad()  #미분을 해서 구한 기울기를 0으로 초기화 해줌, 안하면 이전에 구한 기울기 계속 더해짐
    cost.backward()  #W, b에 대한 기울기가 계산
    optimizer.step() #W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 29661.80078125
100 5.754572868347168
200 5.512386322021484
300 5.281667232513428
400 5.061906814575195
500 4.852423667907715
600 4.652731418609619
700 4.4622650146484375
800 4.280604362487793
900 4.107260704040527
1000 3.941852569580078
1100 3.7838993072509766
1200 3.6330528259277344
1300 3.4889779090881348
1400 3.351316452026367
1500 3.2197258472442627
1600 3.0939736366271973
1700 2.9737014770507812
1800 2.858673334121704
1900 2.748659133911133


In [324]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [325]:
torch.manual_seed(1)

In [326]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [327]:
model = nn.Linear(1,1)  # 입력차원, 출력차원  ->하나의 입력에 하나의 출력이 있다

In [330]:
list(model.parameters())  #w,b 값
#초기 모델 : y=0.5153 * x_train -0.4414 

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [331]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [332]:
for epoch in range(2000):
    
    hx = model(x_train)  #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train)   #cost=torch.mean((hx - y_train) ** 2)
    
    
    optimizer.zero_grad()  #미분을 해서 구한 기울기를 0으로 초기화 해줌, 안하면 이전에 구한 기울기 계속 더해짐
    cost.backward()  #W, b에 대한 기울기가 계산
    optimizer.step() #W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 13.103541374206543
100 0.00279058120213449
200 0.00172441138420254
300 0.0010655784280970693
400 0.0006584661896340549
500 0.0004068926500622183
600 0.0002514346851967275
700 0.00015537298168055713
800 9.601024794392288e-05
900 5.9327696362743154e-05
1000 3.66610438504722e-05
1100 2.2655576685792767e-05
1200 1.3999051589053124e-05
1300 8.65114816406276e-06
1400 5.346103989722906e-06
1500 3.3032331430149497e-06
1600 2.04174443751981e-06
1700 1.2618406799447257e-06
1800 7.801028800713539e-07
1900 4.823282324650791e-07


In [333]:
list(model.parameters()) 

[Parameter containing:
 tensor([[1.9994]], requires_grad=True),
 Parameter containing:
 tensor([0.0014], requires_grad=True)]

In [334]:
new_var =  torch.FloatTensor([[4.0]])

In [335]:
model(new_var)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)

In [337]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [338]:
model=nn.Linear(3,1) # 입력차원, 출력차원

In [339]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True),
 Parameter containing:
 tensor([0.3462], requires_grad=True)]

In [340]:
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

In [341]:
for epoch in range(2000):
    
    hx = model(x_train)  #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train)   #cost=torch.mean((hx - y_train) ** 2)
    
    
    optimizer.zero_grad()  #미분을 해서 구한 기울기를 0으로 초기화 해줌, 안하면 이전에 구한 기울기 계속 더해짐
    cost.backward()  #W, b에 대한 기울기가 계산
    optimizer.step() #W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 42134.70703125
100 5.960053443908691
200 5.654706954956055
300 5.365412712097168
400 5.091428756713867
500 4.831833839416504
600 4.585997104644775
700 4.353074550628662
800 4.132411003112793
900 3.9234554767608643
1000 3.7255024909973145
1100 3.5379719734191895
1200 3.360325574874878
1300 3.19205641746521
1400 3.0326738357543945
1500 2.881699562072754
1600 2.7386722564697266
1700 2.603201150894165
1800 2.4748456478118896
1900 2.353286027908325


In [342]:
new_var = torch.FloatTensor([[90,90,90]])
model(new_var)

tensor([[181.3557]], grad_fn=<AddmmBackward0>)

In [343]:
list(model.parameters())

[Parameter containing:
 tensor([[0.8540, 0.8475, 0.3096]], requires_grad=True),
 Parameter containing:
 tensor([0.3568], requires_grad=True)]